server:
  port: 8602
  port: 8603

spring:
  application:
    name: testservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/

# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true

app:
  ip: localhost