server:
  port: 8605

spring:
  application:
    name: feignclient

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/

feign:
  hystrix:
    enabled: true

turbine:
  aggregator:
    cluster-config: default
    app-config:  testservice
  cluster-name-expression: new String("default")

